# Generated by Django 6.1 on 2026-09-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_rename_person_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referidos', to='people.people'),
        ),
    ]
