# Generated by Django 6.1 on 2026-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_rename_urbanizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='lugar_votacion',
            field=models.CharField(blank=True, help_text='Opcional. Si se deja vacío se guarda sin valor (NULL).', max_length=150, null=True, verbose_name='Lugar de votación'),
        ),
        migrations.AddField(
            model_name='people',
            name='mesa_votacion',
            field=models.CharField(blank=True, help_text='Opcional. Requiere un lugar de votación.', max_length=100, null=True, verbose_name='Mesa de votación'),
        ),
    ]
