# Generated by Django 6.1 on 2026-08-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('contraseña', models.CharField(max_length=128)),
                ('cargo', models.CharField(choices=[('Admin', 'ADMIN'), ('Invitado', 'INVITADO')], default='Invitado', max_length=254)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
