# Generated by Django 6.1 on 2026-08-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
